kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: m0-github-deploy-token
  creationTimestamp: null
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-50"
    checksum: a9df9f602a88897c9d8f9778e44d5d877442e2f637f0e0ef66ac5f2e44fac414
spec:
  template:
    metadata:
      name: m0-github-deploy-token
      creationTimestamp: null
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        helm.sh/hook: pre-install,pre-upgrade
        helm.sh/hook-weight: "-50"
        checksum: a9df9f602a88897c9d8f9778e44d5d877442e2f637f0e0ef66ac5f2e44fac414
    type: kubernetes.io/dockerconfigjson
  encryptedData:
    .dockerconfigjson: AgDfQBFja2GjqsfQ2Bl4s89vF45vx49/s+DEc31ICW6HpDf11Q6z/1/LVf8h321V7b6htZ3oGJk+EdcppjVA6GJC2EYGAg9CFiEPKa8xqqxb1YQptxIneGxNXhL9grdF+xfqLmzkMsW+DnBl9fzvufctch/vEE3lIrmjnJ++dBRqvJWgPNmMJ1iNgi6aFPL6PHLfY+mmhCXhm93WuEtc7lVAV0T1SUgBA2ZvXb5+GL0h0Z3dDDaa+7HQmvRE5ZljIxMS/5t8L9VPxIMexFrpWvVh9vs6b6mvsopyxz0PQNDR2aSLWtE8hXi/2J/7AWHR+1UPoc/5x8wjKdhqmY4w6nlaIvu5akZyEHF4SBkekKisRajb4qyVF+jZdlHAZ3o9iE434ulofWxhYM0r4anCSGWg7Ow4M+fhKFyN9gmKGlsaFXyfiGJWdgWPQDUBaeroLjaZJwZVpFB8PCAYHugTAGuKFbUJcBIUwef3nBn9jgGBRKkbkvBahy4MH1haZtVd863IIwA7ld6kYUcOvR3rlKhXwBpyJKJLFCw2GU8gQXd50sRFcq+BQNazP67SZ7HqKob3qpIm4huSAkg4OEaRmvAkkP71E5Zb2XRXAhTV3O7n14lFjUlwyJFuhZOL+ptT5IhZH8G7t2yEmsioPaUOjLqMPdJl8FSYfGQVaTlCNUNdiFtH3hOo6UARxYsz2TppMXfOIknOlp+xEPObhnqLXlevXb9tpsq4jNmCEv9KkWi6mAI/bWggKXfMSDfB9EXTP7BVIDmzCamX+oWu9GfVcXyN8cV2alXMuwYOlVWkUvGfSd0i0IGYHV9drxryhFEcwa60cs1cinN+oGirv2715fICb1draVPnIUr8/dSM4U6LFkCiqQEaAhkp7p59IMAtHRxyw0pK08hGcq2ig/quFVXIGfWKxabrCI85Rjf5pcdhXZ4psKVlJXccex+NDx9/7fKQnYuFKOIAFPkW
