name: Build & Deploy to PRODUCTION

on:
  workflow_dispatch:

## The actual workflow for the production environment is defined in the deploy-production.yml file in the workflows folder of the production branch

jobs:
  deploy:
    if: github.ref_name == 'production'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Please select the production branch for the workflow run when you want to deploy to Production"
