name: Build & Deploy to STAGING

on:
  workflow_dispatch:

## The actual workflow for the staging environment is defined in the deploy-staging.yml file in the workflows folder of the staging branch

jobs:
  deploy:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Please select the staging branch for the workflow run when you want to deploy to Staging"
