---
on:
  push:
    branches:
      - main
      - tests/**
  pull_request:
    types: [opened]
  schedule:
    - cron: "* 8 * * *" # Run every day at 8am UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: "Dockerfile.tests"
          tags: local-cypress:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
  cypress:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        test_runs: [ "basic1", "basic2" ]
    steps:
      - name: Run Cypress tests
        uses: addnab/docker-run-action@v3
        with:
          image: local-cypress:latest
          options: --env TEST_RUN=${{ matrix.test_runs }}
          run: "/app/entrypoint.sh"
