name: Deploy to DEV

on:
  push:
    branches:
      - 'main'
      - 'feature/**'
      - 'bugfix/**'
  workflow_dispatch:

jobs:
  deploy-to-dev:
    uses: MZero-Labs/devops-templates/.github/workflows/deploy_m0_dev_cluster_pipeline.yml@main
    secrets: inherit
    permissions:
      contents: write
      packages: write
    with:
      HELM_COMPONENTS: ${{ github.event.repository.name }}
