name: publish-static-to-S3-bucket

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  publish-static-to-S3-bucket-job:
    uses: MZero-Labs/devops-templates/.github/workflows/groups/standalone_app_build_and_deploy_s3.yml@main    
    secrets:
       AWS_REGION:            "eu-central-1"
       AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       AWS_S3_BUCKET:         "thething-publish-spog-frontend-dev-p14y"
       SOURCE_DIR:            "./.output/public"