name: Build & Upload to S3 DEV

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  deploy-to-dev:
    uses: MZero-Labs/devops-templates/.github/workflows/s3_buckets_main_dev.yml@main
    secrets: inherit
    permissions:
      contents: write
