name: Build & Upload to S3 STAGING

on:
  push:
    branches:
      - 'staging'
  workflow_dispatch:

jobs:
  deploy-to-dev:
    uses: MZero-Labs/devops-templates/.github/workflows/s3_buckets_main_staging.yml@main
    secrets: inherit
    permissions:
      contents: write
    #with:
      #MASTER_VERSION is used for tagging and release (only on PRODUCTION)
      #MASTER_VERSION: "0"
