name: Build & Upload to S3 PRODUCTION

on:
  workflow_dispatch:

jobs:
  deploy-to-production:
    uses: MZero-Labs/devops-templates/.github/workflows/s3_buckets_main_production.yml@main
    secrets: inherit
    permissions:
      contents: write
    if: github.ref_name == 'production'
  upload-to-ipfs:
    uses: MZero-Labs/devops-templates/.github/workflows/upload_to_ipfs.yml@main
    needs: [ deploy-to-production ]
    secrets: inherit
    if: github.ref_name == 'production'
